# Numpy Practice

In [18]:
import numpy as np

In [35]:
list1d = np.array([1,2,3])
list2d = np.array([[1,2,3],[3,4,5]])
list3d = np.array([[[1,2],[4,5],[3,6]],
                   [[4,5],[5,6],[7,8]]])

In [36]:
print("-------------1d list------------\n", list1d)
print("-------------2d lis-------------\n", list2d)
print("-------------3d list------------\n", list3d)

-------------1d list------------
 [1 2 3]
-------------2d lis-------------
 [[1 2 3]
 [3 4 5]]
-------------3d list------------
 [[[1 2]
  [4 5]
  [3 6]]

 [[4 5]
  [5 6]
  [7 8]]]


## Dimensions, Size, type

In [37]:
listtype = list1d.dtype
print(listtype)

int64


In [38]:
#setting a type
listSmall = np.array([[1,2,3],[4,5,6]], dtype = 'int16')
print(listSmall.dtype)

int16


In [41]:
print("1d array shape = " , list1d.shape)
print("2d array shape = " , list2d.shape)
print("3d array shape = " , list3d.shape)

1d array shape =  (3,)
2d array shape =  (2, 3)
3d array shape =  (2, 3, 2)


In [42]:
print("1d array dimension = ", list1d.ndim)
print("2d array dimension = ", list2d.ndim)
print("3d array dimension = ", list3d.ndim)

1d array dimension =  1
2d array dimension =  2
3d array dimension =  3
