# Numpy Practice

In [18]:
import numpy as np

In [35]:
list1d = np.array([1,2,3])
list2d = np.array([[1,2,3],[3,4,5]])
list3d = np.array([[[1,2],[4,5],[3,6]],
                   [[4,5],[5,6],[7,8]]])

In [36]:
print("-------------1d list------------\n", list1d)
print("-------------2d lis-------------\n", list2d)
print("-------------3d list------------\n", list3d)

-------------1d list------------
 [1 2 3]
-------------2d lis-------------
 [[1 2 3]
 [3 4 5]]
-------------3d list------------
 [[[1 2]
  [4 5]
  [3 6]]

 [[4 5]
  [5 6]
  [7 8]]]


# Dimensions, Size, type, Shape

In [37]:
listtype = list1d.dtype
print(listtype)

int64


In [38]:

listSmall = np.array([[1,2,3],[4,5,6]], dtype = 'int16')
print(listSmall.dtype)

int16


In [41]:
print("1d array shape = " , list1d.shape)
print("2d array shape = " , list2d.shape)
print("3d array shape = " , list3d.shape)

1d array shape =  (3,)
2d array shape =  (2, 3)
3d array shape =  (2, 3, 2)


In [42]:
print("1d array dimension = ", list1d.ndim)
print("2d array dimension = ", list2d.ndim)
print("3d array dimension = ", list3d.ndim)

1d array dimension =  1
2d array dimension =  2
3d array dimension =  3


In [50]:
print("total elements in 1d list", list1d.size)
print("total elements in 2d list", list2d.size)
print("Total elements in 3d list", list3d.size)


total elements in 1d list 3
total elements in 2d list 6
Total elements in 3d list 12


In [52]:
print("Each item in list1d with dtype = ", list1d.dtype, "takes bytes = ", list1d.itemsize)

each item in list1d with dtype =  int64 takes bytes =  8


In [53]:
print("Each item in listSmall with dtype = ", listSmall.dtype , "Takes bytes = ", listSmall.itemsize)

Each item in listSmall with dtype =  int16 Takes bytes =  2


## Total No of Bytes in Array

In [55]:
print("total bytes taken by 1d array = ", list1d.itemsize*list1d.size)
print("\n Or \n")
print("Total bytes can also be calculated with .nbytes as = ", list1d.nbytes)


total bytes taken by 1d array =  24

 Or 

Total bytes can also be calculated with .nbytes as =  24


# Accessing Specific Elements

In [62]:
print("3d Array = ", list3d , " \n \nwith shape = ", list3d.shape)

3d Array =  [[[1 2]
  [4 5]
  [3 6]]

 [[4 5]
  [5 6]
  [7 8]]]  
 
with shape =  (2, 3, 2)


In [65]:
 # Access the 7

list3d[1,2,0] #BECAUSE THERE ARE 2 ELEMENTS IN 3RD DIMENSION AND WE WANT THE SECOND ONE
#BECAUSE THERE ARE 3 ELEMENTS IN EACH 2ND DIMENSION AND WE WANT THE LAST ONE IE THIRD ONE
#BECAUSE THERE ARE 2 ELEMENTS IN EACH SMALLEST ARRAY AND WE WANT THE FIRST ONE

7

# 3d Array looks like this

```
[ ---------------------------------------------------------------
 [------------------------------------------                     |
  [1,2], --------> 2 elements  (first Dim) |                     |
  [4,5],                                   |---> 3 elements(2nd  |
  [3,6]                                    |        Dimension)   |
        ],----------------------------------                     |
                                                                 |
 [                                                   |-> 2 elements (3rd Dim)
  [4,5],                                                         |
  [5,6],                                                         |
  [7,8]                                                          |
        ]                                                        |
          ]-------------------------------------------------------
```


In [70]:
# Access the first 5
print(" The first 5 = ", list3d[0,1,1])

#Access the second 5
print("\n The second 5 = ", list3d[1,0,1])

#Access the first 6
print("\n The First 6 = ", list3d[0,2,1])

#Access the second 6
print("\n The second 6 = ", list3d[1,1,1])

 The first 5 =  5

 The second 5 =  5

 The First 6 =  6

 The second 6 =  6


In [77]:
#print the whole specific dimension
#print the 2nd Element of the second dimension

list3d[:,1,:]

array([[4, 5],
       [5, 6]])

In [82]:
#printing the 2nd element of the third dimension
#which means that I'm printing whole 1st and 2nd 
#dim that occurs in 2nd element of the third dimension

print(list3d[-1, : ,:] )
print("\n or \n")
print("___________________ \n\n")
print(list3d[1, : , :])

[[4 5]
 [5 6]
 [7 8]]

 or 

___________________ 


[[4 5]
 [5 6]
 [7 8]]


In [ ]:
#printing the first element of the first dimension
#for which means printing 